import { BlockExplorerStandard, BlockExplorerType, EndpointAuth, EndpointType } from '../enums'
import { type Network } from '../types'

import { ankr, blast, moonbeamProvider, onerpc, onfinality, pokt } from '../providers'

export const moonbeam = {
    id: 1284,
    name: 'Moonbeam',
    network: 'moonbeam',
    infoUrl: 'https://moonbeam.network',
    docsUrl: 'https://docs.moonbeam.network',
    eipUrl: 'https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-1284.json',
    nativeCurrency: {
        name: 'GLMR',
        symbol: 'GLMR',
        uSymbol: 'aGLMR',
        decimals: 18,
    },
    rpcNodes: {
        pokt: {
            rpcNode: 'pokt',
            type: EndpointType.Authenticated,
            http: [`https://moonbeam-mainnet.gateway.pokt.network/v1/lb/${EndpointAuth.Key}`],
            provider: pokt,
        },
        poktPublic: {
            rpcNode: 'poktPublic',
            type: EndpointType.Public,
            http: ['https://moonbeam-rpc.gateway.pokt.network'],
            provider: pokt,
        },
        blast: {
            rpcNode: 'blast',
            type: EndpointType.Authenticated,
            http: [`https://moonbeam.blastapi.io/${EndpointAuth.Key}`],
            wss: [`wss://moonbeam.blastapi.io/${EndpointAuth.Key}`],
            provider: blast,
        },
        blastPublic: {
            rpcNode: 'blastPublic',
            type: EndpointType.Public,
            http: ['https://moonbeam.public.blastapi.io'],
            wss: ['wss://moonbeam.public.blastapi.io'],
            provider: blast,
        },
        onfinality: {
            rpcNode: 'onfinality',
            type: EndpointType.Public,
            http: ['https://moonbeam.api.onfinality.io/public'],
            wss: ['wss://moonbeam.api.onfinality.io/public-ws'],
            provider: onfinality,
        },
        ankr: {
            rpcNode: 'ankr',
            type: EndpointType.Authenticated,
            http: [`https://rpc.ankr.com/moonbeam/${EndpointAuth.Key}`],
            provider: ankr,
        },
        ankrPublic: {
            rpcNode: 'ankrPublic',
            type: EndpointType.Public,
            http: ['https://rpc.ankr.com/moonbeam'],
            provider: ankr,
        },
        onerpc: {
            rpcNode: 'onerpc',
            type: EndpointType.Public,
            http: ['https://1rpc.io/glmr'],
            provider: onerpc,
        },
        moonbeam: {
            rpcNode: 'moonbeam',
            type: EndpointType.Public,
            http: ['https://rpc.api.moonbeam.network'],
            wss: ['wss://wss.api.moonbeam.network'],
            provider: moonbeamProvider,
        },
        public: {
            rpcNode: 'public',
            type: EndpointType.Public,
            http: ['https://rpc.api.moonbeam.network'],
            wss: ['wss://wss.api.moonbeam.network'],
            provider: moonbeamProvider,
        },
        default: {
            rpcNode: 'default',
            type: EndpointType.Public,
            http: ['https://rpc.api.moonbeam.network'],
            wss: ['wss://wss.api.moonbeam.network'],
            provider: moonbeamProvider,
        },
    },
    blockExplorers: {
        moonbeamSubscan: {
            name: 'Moonbeam Subscan',
            blockExplorer: 'moonbeamSubscan',
            type: BlockExplorerType.Subscan,
            standard: BlockExplorerStandard.None,
            browserUrl: 'https://moonbeam.subscan.io',
            apiUrl: 'https://moonbeam.api.subscan.io',
            docsUrl: 'https://support.subscan.io/#introduction',
        },
        moonbeamExplorer: {
            name: 'Moonbeam Blockchain Explorer',
            blockExplorer: 'moonbeamExplorer',
            type: BlockExplorerType.Blockscout,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://blockscout.moonbeam.network',
            apiUrl: 'https://blockscout.moonbeam.network/api',
            docsUrl: 'https://blockscout.moonbeam.network/api-docs',
        },
        moonscan: {
            name: 'Moonscan',
            blockExplorer: 'moonscan',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://moonscan.io',
            apiUrl: 'https://api-moonbeam.moonscan.io/api',
            docsUrl: 'https://moonscan.io/apis',
        },
        default: {
            name: 'Moonscan',
            blockExplorer: 'default',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://moonscan.io',
            apiUrl: 'https://api-moonbeam.moonscan.io/api',
            docsUrl: 'https://moonscan.io/apis',
        },
    },
    contracts: {
        multicall3: {
            name: 'Multicall V3',
            contract: 'multicall3',
            address: '0xcA11bde05977b3631167028862bE2a173976CA11',
            deployBlock: 609002,
            deployTxHash: '0x4fde2b82529678300f318297ce95aa310f557d37a3346362500f17c042f0aff2',
        },
    },
    testnet: false,
} as const satisfies Network
