import { BlockExplorerStandard, BlockExplorerType, EndpointAuth, EndpointType } from '../enums'
import { type Network } from '../types'

import {
    alchemy,
    ankr,
    blast,
    blockpi,
    infura,
    lava,
    omnia,
    onerpc,
    optimismProvider,
    pokt,
    thirdweb,
} from '../providers'

export const optimisticEthereum = {
    id: 10,
    name: 'Optimism',
    network: 'optimisticEthereum',
    infoUrl: 'https://optimism.io',
    docsUrl: 'https://community.optimism.io',
    eipUrl: 'https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-10.json',
    nativeCurrency: {
        name: 'Ether',
        symbol: 'ETH',
        uSymbol: 'Wei',
        decimals: 18,
    },
    rpcNodes: {
        alchemy: {
            rpcNode: 'alchemy',
            type: EndpointType.Authenticated,
            http: [`https://opt-mainnet.g.alchemy.com/v2/${EndpointAuth.Key}`],
            wss: [`wss://opt-mainnet.g.alchemy.com/v2/${EndpointAuth.Key}`],
            provider: alchemy,
        },
        infura: {
            rpcNode: 'infura',
            type: EndpointType.Authenticated,
            http: [`https://optimism-mainnet.infura.io/v3/${EndpointAuth.Key}`],
            provider: infura,
        },
        lava: {
            rpcNode: 'lava',
            type: EndpointType.Authenticated,
            http: [`https://g.w.lavanet.xyz:443/gateway/optm/rpc-http/${EndpointAuth.Key}`],
            wss: [`wss://g.w.lavanet.xyz:443/gateway/optm/rpc/${EndpointAuth.Key}`],
            provider: lava,
        },
        pokt: {
            rpcNode: 'pokt',
            type: EndpointType.Authenticated,
            http: [`https://optimism-mainnet.gateway.pokt.network/v1/lb/${EndpointAuth.Key}`],
            provider: pokt,
        },
        poktPublic: {
            rpcNode: 'poktPublic',
            type: EndpointType.Public,
            http: ['https://optimism-rpc.gateway.pokt.network'],
            provider: pokt,
        },
        thirdweb: {
            rpcNode: 'thirdweb',
            type: EndpointType.Public,
            http: ['https://optimism.rpc-staging.thirdweb.com'],
            provider: thirdweb,
        },
        ankr: {
            rpcNode: 'ankr',
            type: EndpointType.Authenticated,
            http: [`https://rpc.ankr.com/optimism/${EndpointAuth.Key}`],
            provider: ankr,
        },
        ankrPublic: {
            rpcNode: 'ankrPublic',
            type: EndpointType.Public,
            http: ['https://rpc.ankr.com/optimism'],
            provider: ankr,
        },
        blast: {
            rpcNode: 'blast',
            type: EndpointType.Authenticated,
            http: [`https://optimism-mainnet.blastapi.io/${EndpointAuth.Key}`],
            wss: [`wss://optimism-mainnet.blastapi.io/${EndpointAuth.Key}`],
            provider: blast,
        },
        blastPublic: {
            rpcNode: 'blastPublic',
            type: EndpointType.Public,
            http: ['https://optimism-mainnet.public.blastapi.io'],
            wss: ['wss://optimism-mainnet.public.blastapi.io'],
            provider: blast,
        },
        blockpi: {
            rpcNode: 'blockpi',
            type: EndpointType.Authenticated,
            http: [`https://optimism.blockpi.network/v1/rpc/${EndpointAuth.Key}`],
            wss: [`wss://optimism.blockpi.network/v1/ws/${EndpointAuth.Key}`],
            provider: blockpi,
        },
        blockpiPublic: {
            rpcNode: 'blockpiPublic',
            type: EndpointType.Public,
            http: ['https://optimism.blockpi.network/v1/rpc/public'],
            provider: blockpi,
        },
        onerpc: {
            rpcNode: 'onerpc',
            type: EndpointType.Public,
            http: ['https://1rpc.io/op'],
            provider: onerpc,
        },
        omnia: {
            rpcNode: 'omnia',
            type: EndpointType.Authenticated,
            http: [`https://endpoints.omniatech.io/v1/op/mainnet/${EndpointAuth.Key}`],
            wss: [`wss://endpoints.omniatech.io/v1/op/mainnet/${EndpointAuth.Key}`],
            provider: omnia,
        },
        omniaPublic: {
            rpcNode: 'omniaPublic',
            type: EndpointType.Public,
            http: ['https://endpoints.omniatech.io/v1/op/mainnet/public'],
            provider: omnia,
        },
        optimism: {
            rpcNode: 'optimism',
            type: EndpointType.Public,
            http: ['https://mainnet.optimism.io'],
            provider: optimismProvider,
        },
        public: {
            rpcNode: 'public',
            type: EndpointType.Public,
            http: ['https://mainnet.optimism.io'],
            provider: optimismProvider,
        },
        default: {
            rpcNode: 'default',
            type: EndpointType.Public,
            http: ['https://mainnet.optimism.io'],
            provider: optimismProvider,
        },
    },
    blockExplorers: {
        optimismExplorer: {
            name: 'Optimism Blockchain Explorer',
            blockExplorer: 'optimismExplorer',
            type: BlockExplorerType.Blockscout,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://blockscout.com/optimism/mainnet',
            apiUrl: 'https://blockscout.com/optimism/mainnet/api',
            docsUrl: 'https://blockscout.com/optimism/mainnet/api-docs',
        },
        optimismscan: {
            name: 'Optimism Etherscan',
            blockExplorer: 'optimismscan',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://optimistic.etherscan.io',
            apiUrl: 'https://api-optimistic.etherscan.io/api',
            docsUrl: 'https://docs.optimism.etherscan.io',
        },
        default: {
            name: 'Optimism Etherscan',
            blockExplorer: 'default',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://optimistic.etherscan.io',
            apiUrl: 'https://api-optimistic.etherscan.io/api',
            docsUrl: 'https://docs.optimism.etherscan.io',
        },
    },
    contracts: {
        multicall3: {
            name: 'Multicall V3',
            contract: 'multicall3',
            address: '0xca11bde05977b3631167028862be2a173976ca11',
            deployBlock: 4286263,
            deployTxHash: '0xb62f9191a2cf399c0d2afd33f5b8baf7c6b52af6dd2386e44121b1bab91b80e5',
        },
    },
    testnet: false,
} as const satisfies Network
