import { BlockExplorerStandard, BlockExplorerType, EndpointAuth, EndpointType } from '../enums'
import { type Network } from '../types'

import {
    alchemy,
    ankr,
    blast,
    blockpi,
    chainstack,
    infura,
    lava,
    omnia,
    pokt,
    polygonProvider,
} from '../providers'

export const polygonMumbai = {
    id: 80001,
    name: 'Polygon Mumbai',
    network: 'polygonMumbai',
    infoUrl: 'https://polygon.technology',
    docsUrl: 'https://wiki.polygon.technology',
    eipUrl: 'https://github.com/ethereum-lists/chains/blob/master/_data/chains/eip155-80001.json',
    nativeCurrency: {
        name: 'MATIC',
        symbol: 'MATIC',
        uSymbol: 'Wei',
        decimals: 18,
    },
    rpcNodes: {
        alchemy: {
            rpcNode: 'alchemy',
            type: EndpointType.Authenticated,
            http: [`https://polygon-mumbai.g.alchemy.com/v2/${EndpointAuth.Key}`],
            wss: [`wss://polygon-mumbai.g.alchemy.com/v2/${EndpointAuth.Key}`],
            provider: alchemy,
        },
        infura: {
            rpcNode: 'infura',
            type: EndpointType.Authenticated,
            http: [`https://polygon-mumbai.infura.io/v3/${EndpointAuth.Key}`],
            provider: infura,
        },
        pokt: {
            rpcNode: 'pokt',
            type: EndpointType.Authenticated,
            http: [`https://polygon-mumbai.gateway.pokt.network/v1/lb/${EndpointAuth.Key}`],
            provider: pokt,
        },
        lava: {
            rpcNode: 'lava',
            type: EndpointType.Authenticated,
            http: [`https://g.w.lavanet.xyz:443/gateway/polygon1t/rpc-http/${EndpointAuth.Key}`],
            wss: [`wss://g.w.lavanet.xyz:443/gateway/polygon1t/rpc/${EndpointAuth.Key}`],
            provider: lava,
        },
        blast: {
            rpcNode: 'blast',
            type: EndpointType.Authenticated,
            http: [`https://polygon-testnet.blastapi.io/${EndpointAuth.Key}`],
            wss: [`wss://polygon-testnet.blastapi.io/${EndpointAuth.Key}`],
            provider: blast,
        },
        blastPublic: {
            rpcNode: 'blastPublic',
            type: EndpointType.Public,
            http: ['https://polygon-testnet.public.blastapi.io'],
            wss: ['wss://polygon-testnet.public.blastapi.io'],
            provider: blast,
        },
        blockpi: {
            rpcNode: 'blockpi',
            type: EndpointType.Authenticated,
            http: [`https://polygon-mumbai.blockpi.network/v1/rpc/${EndpointAuth.Key}`],
            wss: [`wss://polygon-mumbai.blockpi.network/v1/ws/${EndpointAuth.Key}`],
            provider: blockpi,
        },
        blockpiPublic: {
            rpcNode: 'blockpiPublic',
            type: EndpointType.Public,
            http: ['https://polygon-mumbai.blockpi.network/v1/rpc/public'],
            provider: blockpi,
        },
        ankr: {
            rpcNode: 'ankr',
            type: EndpointType.Authenticated,
            http: [`https://rpc.ankr.com/polygon_mumbai/${EndpointAuth.Key}`],
            provider: ankr,
        },
        ankrPublic: {
            rpcNode: 'ankrPublic',
            type: EndpointType.Public,
            http: ['https://rpc.ankr.com/polygon_mumbai'],
            provider: ankr,
        },
        omnia: {
            rpcNode: 'omnia',
            type: EndpointType.Authenticated,
            http: [`https://endpoints.omniatech.io/v1/matic/mumbai/${EndpointAuth.Key}`],
            wss: [`wss://endpoints.omniatech.io/v1/matic/mumbai/${EndpointAuth.Key}`],
            provider: omnia,
        },
        omniaPublic: {
            rpcNode: 'omniaPublic',
            type: EndpointType.Public,
            http: ['https://endpoints.omniatech.io/v1/matic/mumbai/public'],
            provider: omnia,
        },
        polygon: {
            rpcNode: 'polygon',
            type: EndpointType.Public,
            http: ['https://rpc-mumbai.matic.today'],
            provider: polygonProvider,
        },
        chainstack: {
            rpcNode: 'chainstack',
            type: EndpointType.Public,
            http: ['https://matic-mumbai.chainstacklabs.com'],
            provider: chainstack,
        },
        public: {
            rpcNode: 'public',
            type: EndpointType.Public,
            http: ['https://matic-mumbai.chainstacklabs.com'],
            provider: chainstack,
        },
        default: {
            rpcNode: 'default',
            type: EndpointType.Public,
            http: ['https://matic-mumbai.chainstacklabs.com'],
            provider: chainstack,
        },
    },
    blockExplorers: {
        polygonScan: {
            name: 'Mumbai PolygonScan',
            blockExplorer: 'polygonScan',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://mumbai.polygonscan.com',
            apiUrl: 'https://api-testnet.polygonscan.com',
            docsUrl: 'https://docs.polygonscan.com/v/mumbai-polygonscan',
        },
        default: {
            name: 'Mumbai PolygonScan',
            blockExplorer: 'default',
            type: BlockExplorerType.Etherscan,
            standard: BlockExplorerStandard.EIP3091,
            browserUrl: 'https://mumbai.polygonscan.com',
            apiUrl: 'https://api-testnet.polygonscan.com',
            docsUrl: 'https://docs.polygonscan.com/v/mumbai-polygonscan',
        },
    },
    contracts: {
        multicall3: {
            name: 'Multicall V3',
            contract: 'multicall3',
            address: '0xca11bde05977b3631167028862be2a173976ca11',
            deployBlock: 25444704,
            deployTxHash: '0xec60edd53f24800ae2f27ff3c364b05e86cc26165fc6183aca3a879e90f3d345',
        },
    },
    testnet: true,
    mainnetId: 137,
} as const satisfies Network
